### ISSUE TITLE
Modify the todo API behavior

### ISSUE THREAD

**Issue by Yohuan** [Yohuan/todo_list#21]
# Todo Resource

- [x] add `object` attribute as `todo`
- [x] add `todo_` prefix in its ID
- [x] add `creationTime` attribute

# GET /todos

- [x] Return a list object

ex:

```js
{
  "object": "list",
  "has_more": false,
  "data": [
    {...},
    {...},
    {...}
  ]
}
```

# POST /todos

-  [x] return the created todo in response body

# PUT /todos/{todoId}

- [x] Return the modified resource with 200
- [x] Request body does not have to include the whole object
